name: Build master

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [3.0.100]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Restore local tools
        run: dotnet tool restore
      - name: Build
        run: dotnet fake run build.fsx